#ifndef _COMPAT_LINUX_BITOPS_H
#define _COMPAT_LINUX_BITOPS_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/bitops.h>

#ifndef BIT_ULL
#define BIT_ULL(nr)    (1ULL << (nr))
#endif

#ifndef BITS_PER_TYPE
#define BITS_PER_TYPE(type) (sizeof(type) * BITS_PER_BYTE)
#endif

#endif /* _COMPAT_LINUX_BITOPS_H */
