#ifndef _COMPAT_LINUX_BUILD_BUG_H
#define _COMPAT_LINUX_BUILD_BUG_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/build_bug.h>

/* Force a compilation error if a constant expression is not a power of 2 */
#ifndef __BUILD_BUG_ON_NOT_POWER_OF_2
#define __BUILD_BUG_ON_NOT_POWER_OF_2(n)        \
        BUILD_BUG_ON(((n) & ((n) - 1)) != 0)
#endif

#endif /* _COMPAT_LINUX_BUILD_BUG_H */
