#ifndef _COMPAT_LINUX_FIRMWARE_H
#define _COMPAT_LINUX_FIRMWARE_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/firmware.h>

#endif /* _COMPAT_LINUX_FIRMWARE_H */
