#ifndef _COMPAT_LINUX_LOCKDEP_H
#define _COMPAT_LINUX_LOCKDEP_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/lockdep.h>

#ifndef lockdep_assert_held_write
#define lockdep_assert_held_write(l)    do {                    \
	WARN_ON(debug_locks && !lockdep_is_held_type(l, 0));    \
} while (0)
#endif

#endif /* _COMPAT_LINUX_LOCKDEP_H */
