# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_INFINIBAND_SRP)			+= ib_srp.o
obj-$(CONFIG_INFINIBAND_SRP_DUMMY)		+= ib_srp.o

ifeq ($(CONFIG_INFINIBAND_SRP_DUMMY),m)
ib_srp-y := ib_srp_dummy.o
endif
