#ifndef _COMPAT_NET_IPV6_H
#define _COMPAT_NET_IPV6_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <net/ipv6.h>

#define ipv6_addr_copy(a, b) (*(a) = *(b))

#ifndef HAVE_IP6_DST_HOPLIMIT
#define ip6_dst_hoplimit  LINUX_BACKPORT(ip6_dst_hoplimit)
int ip6_dst_hoplimit(struct dst_entry *dst);
#endif

#endif /* _COMPAT_NET_IPV6_H */
